mrc-1753_frontend Rename version to project in front end
mrc-ide/hint pull request #311
Opened 2020-08-27 11:15 UTC by EmmaLRussell

2020-08-27 17:49 UTC, richfitz requested changes
I found one possible leftover (versionId).

In the database interface, are `version_file` and `project_version` also possibly related to this but have done the double move already?

2020-08-27 17:49 UTC, richfitz commented on src/app/static/src/app/types.ts
> -export interface Version {
On line 84 below, should that be versionId, with corresponding changes in a number of places:

```
src/app/static/src/app/types.ts
84:    versionId: number,

src/app/static/src/app/components/projects/ProjectHistory.vue
50:        loadSnapshot: (event: Event, versionId: number, snapshotId: string) => void,
64:           loadSnapshot(event: Event, versionId: number, snapshotId: string) {
66:               this.loadAction({versionId, snapshotId});

src/app/static/src/app/store/projects/actions.ts
76:            .get<SnapshotDetails>(`project/${snapshot.versionId}/snapshot/${snapshot.snapshotId}`)

src/app/static/src/tests/integration/projects.itest.ts
87:        const versionId = createdProject.id;
90:            actions.loadSnapshot({commit, dispatch, state, rootState} as any, {versionId, snapshotId});

src/app/static/src/tests/projects/actions.test.ts
286:        actions.loadSnapshot({commit, dispatch, state, rootState} as any, {versionId: 1, snapshotId: "testSnapshot"});
303:        actions.loadSnapshot({commit, dispatch, state, rootState} as any, {versionId: 1, snapshotId: "testSnapshot"});

src/app/static/src/tests/components/projects/projectHistory.test.ts
139:        expect(mockLoad.mock.calls[0][1]).toStrictEqual({versionId: 1, snapshotId: "s11"});
```

2020-08-28 08:27 UTC, EmmaLRussell commented
Well spotted! Yes, I changed both database tables and related code in one go.

> I found one possible leftover (versionId).
> 
> In the database interface, are `version_file` and `project_version` also possibly related to this but have done the double move already?

2020-08-28 09:47 UTC, richfitz approved these changes

2020-08-28 09:47 UTC, merged