mrc-1963 - Add indication that a project was shared by someone else
mrc-ide/hint pull request #454
Opened 2021-01-11 18:01 UTC by carbowizzy

## Description

This PR adds indication that a project was shared by someone else, a user is able to see the email addresses of a user whose project is shared. 

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-01-13 10:13 UTC, EmmaLRussell requested changes
This is really neat and works great! :+1: 

I think it would be even nicer if the 'Shared by' column was not visible if the user does not have any projects shared with them, as will probably be the case for most users. Should just be a case of adding a computed property `anySharedProjects` to the component, which returns a count of the filtered project list where sharedBy is truthy, and `v-if`-ing the relevant elements on that. In that case we could donate the extra column width to the project name  column. Happy for that to go into a separate ticket though, if you want to add one to the sprint.

2021-01-13 10:13 UTC, EmmaLRussell commented on src/app/static/src/app/store/translations/locales.ts
> +    sharedBy: "partagé par",
I think we'll want to make this capitalised: "Partagé par"

2021-01-13 10:13 UTC, EmmaLRussell commented on src/app/static/src/tests/components/projects/projectHistory.test.ts
> +        expectTranslated(headers.at(9), "SharedBy", "partagé par", store);
Need a test for the shared by value too

2021-01-13 16:19 UTC, carbowizzy commented on src/app/static/src/app/store/translations/locales.ts
> +    sharedBy: "SharedBy",
I actually tried to manage the space as the text gets truncated.

2021-01-13 16:21 UTC, carbowizzy commented on src/app/src/main/kotlin/org/imperial/mrc/hint/models/Project.kt
> +    constructor(id: Int, name: String, versions: List<Version>) : this( id,  name, "", versions)
You are right, I tried to use the optional param but wasn't working so I abandoned it. I figured why it didn't work, it's now refactored.

2021-01-13 16:22 UTC, carbowizzy commented on src/app/src/main/kotlin/org/imperial/mrc/hint/db/ProjectRepository.kt
> +    override fun saveClonedProject(userId: String, projectName: String, sharedBy: String): Int
I will create a new ticket to get the column hidden when not in use.

2021-01-14 12:17 UTC, EmmaLRussell approved these changes

2021-01-14 12:18 UTC, EmmaLRussell commented
Looks good - could you just fix the version conflict then go ahead and merge.

2021-01-14 12:47 UTC, merged