mrc-2115 - Hide project history column(shared by) when no data
mrc-ide/hint pull request #457
Opened 2021-01-15 12:33 UTC by carbowizzy

## Description

Please describe your changes here

## Type of version change
_Delete as appropriate_

Minor 

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-01-15 16:25 UTC, Nicolas-Dolan requested changes
Thanks for your work here. I think perhaps the columns are getting too crowded and I don't think we can fit another containing an email address. There's also the issue of the version columns becoming misaligned (which I'm not sure if that predates this pr or not). Anyway perhaps another solution would be to have 'Shared by: xxxxx' appear under the project name if it has been shared. @EmmaLRussell what do you think? Sorry Lekan if this creates extra work for you.

![image](https://user-images.githubusercontent.com/57633087/104752161-3f89e780-574e-11eb-9565-61aac780d866.png)

2021-01-18 14:49 UTC, EmmaLRussell commented
Good idea @Nicolas-Dolan about putting 'shared by' underneath the project, I think that could work too, although might be fiddly to get the vertical spacing right to not look messy with a mix of shared/unshared projects. I don't think the extra column looks *too* bad, particularly since we're going to hide it for users who have no projects shared with them (probably most users other than admins), though I agree it is getting pretty busy. Happy with either approach, and to await user feedback, 

> 
> Thanks for your work here. I think perhaps the columns are getting too crowded and I don't think we can fit another containing an email address. There's also the issue of the version columns becoming misaligned (which I'm not sure if that predates this pr or not). Anyway perhaps another solution would be to have 'Shared by: xxxxx' appear under the project name if it has been shared. @EmmaLRussell what do you think? Sorry Lekan if this creates extra work for you.
> 
> ![image](https://user-images.githubusercontent.com/57633087/104752161-3f89e780-574e-11eb-9565-61aac780d866.png)

2021-01-18 15:07 UTC, EmmaLRussell reviewed
Actually, one advantage to putting the sharedBy underneath as @Nicolas-Dolan suggests is that currently the email address does (usually) overflow the container, which means it will be asymmetrically hidden in narrow windows. So maybe that is the best approach to go with if you can bear it. In which case, it would be probably be better to abandon this PR and make a new ticket to reimplement shared by display .

2021-01-20 10:23 UTC, EmmaLRussell reviewed
Thanks for this - looks good to me, I think the small text is pretty neat. Could you just update the version comment, then go ahead and merge.

2021-01-20 10:23 UTC, EmmaLRussell commented on NEWS.md
>  * Hide project history column(shared by) when no data
This comment should be updated to more clearly reflect the actual changes now being made.

2021-01-20 10:23 UTC, EmmaLRussell commented on src/app/static/src/app/components/projects/ProjectHistory.vue
> +            getTranslatedValue(key: string) {
Nice rename :+1:

2021-01-20 10:58 UTC, merged