Mrc 2565 Add validation to survey and program (SAP) input on Baseline step
mrc-ide/hint pull request #530
Opened 2021-08-18 15:38 UTC by carbowizzy

Add validation to survey and program (SAP) input on Baseline step

## Type of version change
_Delete as appropriate_

Minor 

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-08-19 11:57 UTC, carbowizzy commented
I have also left the RootState  reset for Survey and Program as it because the states still work independently of each other and can be used together seamlessly.

2021-08-19 16:04 UTC, mwoodbri requested changes
I'm lacking some guidance on how to test this, but it works how I'd assume - when all files have been uploaded  in step 1 you can go to either step 2 or 3.

A couple of minor comments inline.

Slight concern that when I first go to the app in my browser it's complaining about not be able to load my data - which implies some inconsistency in format, despite us aiming for backwards compatibility. But there might be a simple explanation for that?

Finally, ticket says:
> Modify root state, change “resetState” behaviour for Baseline and SAP to account for new validation behaviour

But I can't see anything related in this PR? So either the ticket or the code will need to be updated.

2021-08-19 16:38 UTC, EmmaLRussell reviewed
Works for me, as I would expect it. I wonder if we do need to revisit the validation rules - as  things stand, if you remove a baseline file, it silently clears any SAP files which are loaded. This makes some sense for the pjnz/geojson, which are fundamental to the project, but less so for the population file, and it does seem more confusing that this happens now that all files are on the same step together. It would be good to discuss this with the Naomi team to check what their preferred behaviour would be - that could go into another ticket or this one.

2021-08-19 16:38 UTC, EmmaLRussell commented on src/app/static/src/app/store/stepper/getters.ts
> +            2: rootGetters['baseline/complete'] && rootGetters['metadata/complete'] && rootGetters['surveyAndProgram/complete'],
Seems a bit odd to include baseline and metadata here, but I guess this is going to get removed in the next ticket anyway.

2021-08-19 16:38 UTC, EmmaLRussell commented on src/app/static/src/tests/components/stepper.test.ts
> +        expect([2, 3, 4, 5].filter(i => steps.at(i).props().enabled).length).toBe(1);
```suggestion
        expect(steps.at(2).props().enabled).toBe(true);
        expect([3, 4, 5].filter(i => steps.at(i).props().enabled).length).toBe(0);
```

2021-08-19 16:38 UTC, EmmaLRussell commented on src/app/static/src/tests/components/stepper.test.ts
> +    it("Review inputs step is enabled when baseline step is complete", () => {
Should really have two tests to test both that Review inputs is *not* enabled when we have only completedBaselineState, and also that it is enabled  and complete (and subsequent step is enabled) when we have both completedBaselineState and completeSurveyAndProgram state. And rename each test accordingly.

2021-08-19 16:49 UTC, EmmaLRussell commented on src/app/static/src/app/store/stepper/getters.ts
> +            2: rootGetters['baseline/complete'] && rootGetters['metadata/complete'] && rootGetters['surveyAndProgram/complete'],
Ignore this comment, this is right enough

2021-08-20 09:26 UTC, mwoodbri commented
> Works for me, as I would expect it. I wonder if we do need to revisit the validation rules - as things stand, if you remove a baseline file, it silently clears any SAP files which are loaded. This makes some sense for the pjnz/geojson, which are fundamental to the project, but less so for the population file, and it does seem more confusing that this happens now that all files are on the same step together. It would be good to discuss this with the Naomi team to check what their preferred behaviour would be - that could go into another ticket or this one.

I ignored this due to consistency with current behaviour, and additionally I guess that the files are never "lost" i.e. they can either be re-attached from your local machine or from ADR. But agree that at least a warning would be more user-friendly - if the science team consider it a priority.

2021-08-20 09:28 UTC, mwoodbri approved these changes
I haven't been able to reproduce the "unable to load data error" so hopefully just a problem at my end (though I see it's a concern for mrc-2566).

So looking good!

2021-08-20 09:39 UTC, EmmaLRussell approved these changes

2021-08-23 09:09 UTC, merged