Mrc 2223 clone add enter key event to create project input field
mrc-ide/hint pull request #540
Opened 2021-09-06 11:47 UTC by carbowizzy

Adds enter event to create project field. A user can create a new project when he/she press enter button.

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-09-06 16:12 UTC, EmmaLRussell requested changes
> There's really no need to waste time reviewing, it's been reviewed in mrc-2223 before.

Yes, but think what exciting new inconsistencies with master could have crept in since then! :laughing: 

(Actually, it still works fine, but NEWS.md needs a little attention)

2021-09-06 16:12 UTC, EmmaLRussell commented on NEWS.md
> +
```suggestion

```
Seem to have ended up with two version updates for this change.

2021-09-07 12:40 UTC, EmmaLRussell approved these changes

2021-09-08 14:02 UTC, Nicolas-Dolan approved these changes

2021-09-08 14:02 UTC, merged