mrc-2582 Input time series table
mrc-ide/hint pull request #554
Opened 2021-09-22 14:19 UTC by EmmaLRussell

## Description

Please describe your changes here

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-09-27 10:11 UTC, mwoodbri reviewed
Design and implementation both look very good to me. A couple of comments inline, and a couple of questions below. Only other observation with hindsight is that it might have made sense, if possible, to break this into two PRs: one to split existing table into two components, and another to add generic table on top.

1. This is a part of the app I haven't worked on, so this is definitely a question rather than an accusation, but should I always see a table below the bar chart? I am in some instances, but not here, and just wondering why:
![Screenshot from 2021-09-27 10-57-58](https://user-images.githubusercontent.com/1724545/134888890-8fe99af7-6f6a-4496-a382-0074bd2d9602.png)

2. There seems to be change (potentially a regression?) in how table values are displayed (before and after):
![Screenshot from 2021-09-27 11-00-55](https://user-images.githubusercontent.com/1724545/134889002-0f1d25ec-dd36-40a3-b85c-a55cfaf44c3d.png)

![Screenshot from 2021-09-27 11-01-19](https://user-images.githubusercontent.com/1724545/134889014-b6181bd5-bacc-4dc9-b70d-bb36d1832e6b.png)

2021-09-27 12:28 UTC, carbowizzy requested changes
Looks good and works well. 

A big concern for me is the extra hyphen as seen in @mwoodbri screenshot above. I have also added some suggestion, you have not really changed some of these codes but since you have branched out a component from it, it would be nice to attend to them.

2021-09-28 16:14 UTC, EmmaLRussell commented on src/app/static/src/app/components/plots/table/Table.vue
> +                    <slot :name="slot" v-bind="props" />
This was the culprit responsible for the rogue additional '-' lines... :facepalm:

2021-09-28 16:21 UTC, EmmaLRussell commented
> should I always see a table below the bar chart? 

@mwoodbri You should, yes. I am seeing the table for the Antarctica dataset with my ADR key, running locally. From your screenshot, I'm a bit suspicious of the area filter saying "MWI (unknown)" - that suggests something's gone a bit wrong with the area filter, which could be impacting the table too. Which dataset were you using, or were you using local files?

2021-09-28 16:35 UTC, EmmaLRussell commented
> I think we could fetch data differently as well, header columns in different array and data different array. This would have reduced a lot of filtering/ data manipulation.

We're going to be changing the input time series response slightly to replace 'filters' with 'columns', though the structure will be essentially the same. As discussed earlier, I think a general refactor of how we handle metadata vs data, clarifying responsibilities for labelling, and source of truth for metadata etc would be something valuable to tackle after the workshops, and that could include agreeing on most tractable data structures for readable front end code.

2021-09-28 16:41 UTC, EmmaLRussell commented on src/app/static/src/app/components/genericChart/GenericChartTable.vue
> +                        friendlyRow[column.data.columnId] = friendlyValue;
Not sure about this one. This is already a really long line and I don't really want to make it even longer. I'll change it if you feel strongly about it, but I think readability impaired by line length wins out over condensing lines here.

2021-09-28 17:06 UTC, mwoodbri commented
> > should I always see a table below the bar chart?
> 
> @mwoodbri You should, yes. I am seeing the table for the Antarctica dataset with my ADR key, running locally. From your screenshot, I'm a bit suspicious of the area filter saying "MWI (unknown)" - that suggests something's gone a bit wrong with the area filter, which could be impacting the table too. Which dataset were you using, or were you using local files?

Ok - sorry - Burundi but I was comparing this branch with deployed version, rather than with master running locally. Actually an artefact of mock model. Can be ignored.

2021-09-29 08:39 UTC, mwoodbri commented on src/app/static/src/tests/components/plots/table/table.test.ts
> +    //TODO: test for rendering slots
Presumably referring to [this](https://github.com/mrc-ide/hint/pull/554/files#diff-573f702159974d05c90d5fd1eb84d452fec223b1b0e919022fe568431c351f15R161)?

2021-09-29 08:41 UTC, mwoodbri approved these changes

2021-09-29 08:47 UTC, EmmaLRussell commented on src/app/static/src/tests/components/plots/table/table.test.ts
> +    //TODO: test for rendering slots
Yes!

2021-09-29 14:26 UTC, Nicolas-Dolan approved these changes

2021-09-30 11:39 UTC, carbowizzy approved these changes
LGTM

just conflicts to resolve

2021-09-30 16:42 UTC, merged