Mrc 2757 Add DataExploration app component
mrc-ide/hint pull request #612
Opened 2021-11-12 13:07 UTC by LekanAnni

## Description

Please describe your changes here

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-11-15 16:27 UTC, hillalex requested changes
Works great. Small tidy ups to the code requested inline.

I notice that the ADR dataset is not persisted on a page refresh, I think this is because we are not actually persisting anything to local storage for this app yet (the ADR key and input files are saved to the db, hence why they persist) so have added a ticket for that: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2773. 
Perhaps tomorrow we can briefly estimate and decide whether to pull that one in to this sprint.

2021-11-15 16:27 UTC, hillalex commented on src/app/static/src/app/components/files/ManageFile.vue
> +            dataExplorationMode: mapStatePropByName(null, "dataExplorationMode"),
Can this be pulled out into a mixin?

2021-11-15 16:27 UTC, hillalex commented on src/app/static/src/tests/components/uploadInputs/fileUploads.ts
> +import {emptyState} from "../../../app/root";
unused imports?

2021-11-15 16:27 UTC, hillalex commented on src/app/static/src/tests/components/files/manageFile.test.ts
> +    const createStore = (customStore: any = emptyState(), requireConfirmation = false) => {
cant this type not be `DataExplorationState`? and similarly in other test suites above

2021-11-16 09:37 UTC, EmmaLRussell reviewed
This works great. But I'm not sure why we're not matching the mockups in terms of the appearance of the back/continue buttons? I know the prototype didn't, but I thought the assumption was that we'd match the main app here in the real implementation. Is this not the case?

2021-11-16 09:37 UTC, EmmaLRussell commented on src/app/static/src/app/components/dataExploration/DataExploration.vue
> +            <adr-integration></adr-integration>
I'm assuming we should hide ADR Integraton if we're on Step 2, same as for the main app? That's what's shown in the [mockups](https://docs.google.com/presentation/d/1bX7WnIy9Thlub_4Uo17uWlA6f07oicOc/edit#slide=id.p5)

2021-11-16 09:37 UTC, EmmaLRussell commented on src/app/static/src/app/components/dataExploration/DataExploration.vue
> +            </button>
I guess we should also disable back if step === 1 and disable next if step === 2

2021-11-16 09:37 UTC, EmmaLRussell commented on src/app/static/src/tests/dataExploration/getters.test.ts
> +    it(`return true if use is guest`, () => {
```suggestion
    it(`isGuest returns true if user is guest`, () => {
```

2021-11-16 09:37 UTC, EmmaLRussell commented on src/app/static/src/tests/dataExploration/getters.test.ts
> +    it(`return false if user is not guest`, () => {
```suggestion
    it(`isGuest returns false if user is not guest`, () => {
```

2021-11-16 12:07 UTC, hillalex reviewed
Related to my previous comment about local storage, noticed another weird artefact of the current code - if you first log in to the regular app and select a dataset, then switch to explore mode, the selected dataset appears but no files, because the `baseline` module is reading from local storage but the backend session has been cleared. Should be resolved by checking for data exploration mode in the local storage manager `getState` function and only returning state for the correct app mode. Just noting here and will add to the existing ticket around local storage.

2021-11-16 12:07 UTC, hillalex commented on src/app/static/src/tests/components/adr/selectDataset.test.ts
> +    const getStore = (baselineProps: Partial<BaselineState> = {}, adrProps: Partial<ADRState> = {}, requireConfirmation: boolean = false, customStore: any = mockRootState()) => {
Suggest `any` -> `DataExplorationState` and `customStore` -> `state`

2021-11-16 12:38 UTC, LekanAnni commented
> Related to my previous comment about local storage, noticed another weird artefact of the current code - if you first log in to the regular app and select a dataset, then switch to explore mode, the selected dataset appears but no files, because the `baseline` module is reading from local storage but the backend session has been cleared. Should be resolved by checking for data exploration mode in the local storage manager `getState` function and only returning state for the correct app mode. Just noting here and will add to the existing ticket around local storage.

Yes of course , I thought you mentioned you would create a ticket for that....

2021-11-16 16:53 UTC, EmmaLRussell reviewed
Looks good in terms of hiding ADR component in step 2, and disable button behaviour, but still think we should match the Back/Continue navigation from the main app, as shown in the mockups. The buttons at the bottom of the page mean you scroll all the way down to bottom of table to navigate back. You should just be able to re-use the `StepperNavigation` component I think?

2021-11-17 10:00 UTC, LekanAnni commented
> Looks good in terms of hiding ADR component in step 2, and disable button behaviour, but still think we should match the Back/Continue navigation from the main app, as shown in the mockups. The buttons at the bottom of the page mean you scroll all the way down to bottom of table to navigate back. You should just be able to re-use the `StepperNavigation` component I think?

I suppose we can also have back/continue at the bottom as well as the top, right ?

2021-11-17 12:52 UTC, hillalex approved these changes
Looks great, thanks

2021-11-17 14:10 UTC, EmmaLRussell approved these changes
:+1: Nice, just needs conflicts resolved.

2021-11-17 14:57 UTC, merged