Mrc 2778
mrc-ide/hint pull request #625
Opened 2021-11-17 16:40 UTC by EmmaLRussell

## Description

Please describe your changes here

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-11-18 10:43 UTC, EmmaLRussell commented on src/app/static/src/app/components/genericChart/Plotly.vue
> +        <div v-if="rendering" class="text-center mt-4" style="position: absolute; top: 0; width: 100%;">
Make the spinner absolute position so it shows even if user has scrolled down through the subplots. The positioned parent for this is actually the chartContainer's parent in GenericChart

2021-11-18 13:42 UTC, LekanAnni requested changes
Looking good.

Chart is significantly slow, I didn't experience any crash though.

- It still takes almost 20s for the chart to display.
- toggling between tabs is noticeably slow 
- when ANC testing data is loaded, and then toggle to and back, it still takes 20s to reload chart. Perhaps you could look into caching data.
- quarterly control takes time to get populated, obviously waiting for data to be loaded.
- selecting data source takes a significant amount of time to respond.

After several attempts the app finally crashed.

With large dataset, I think it will be slower and unusable when it's deployed to production server.

2021-11-18 13:50 UTC, EmmaLRussell commented
> With large dataset, I think it will be slower and unusable when it's deployed to production server.

This is the full DRC dataset, which is one of the largest, so I don't think prod will be any larger. We do need to test with Nigeria data too though, by the sounds of it. 

It's not really a data caching issue, the actual loading and re-filtering of the data is pretty quick. The delay is in re-rendering the changed data in Plotly. We are a doing a full re-render, which we need to do because of the number of subplots changing between filter selections. 

All the issues you mention will, I think, be addressed by adding paging ([ticket](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2799)). But the improvements in this branch should help with smaller datasets.

2021-11-18 17:45 UTC, hillalex approved these changes
No doubt these are improvements but clearly some way to go. Haven't benchmarked these against our use case but they look worth trying, I suspect especially the `autorange` and the `Plotly.react`: https://www.somesolvedproblems.com/2018/07/how-do-i-make-plotly-faster.html

Although rendering is the main bottleneck it does look as though the data manipulation is also taking a while, judging by the way the page hangs after changing a filter but before the chart loading spinner starts. I think worth digging into the code to see if further optimisations can be made there.

2021-11-18 18:01 UTC, EmmaLRussell commented
> No doubt these are improvements but clearly some way to go. Haven't benchmarked these against our use case but they look worth trying, I suspect especially the `autorange` and the `Plotly.react`: https://www.somesolvedproblems.com/2018/07/how-do-i-make-plotly-faster.html
> 
> Although rendering is the main bottleneck it does look as though the data manipulation is also taking a while, judging by the way the page hangs after changing a filter but before the chart loading spinner starts. I think worth digging into the code to see if further optimisations can be made there.

I don't think `Plotly.react` is an option -we were using that before but it doesn't cope well with new data with a different number of subplots. I'll have a look at `autorange`.

Yes, the filtering itself it taking ~1s. Might be able to find some improvements there.

2021-11-19 09:30 UTC, LekanAnni approved these changes

2021-11-19 10:24 UTC, EmmaLRussell commented
I've added another ticket for finding further performance improvements: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2801
..and am also implementing paging in mrc-2799

2021-11-19 10:58 UTC, merged