mrc-2833 unfreeze default barchart selections so they can be mutated
mrc-ide/hint pull request #643
Opened 2021-12-09 15:26 UTC by EmmaLRussell

## Description

Please describe your changes here

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2021-12-10 10:41 UTC, Nicolas-Dolan reviewed
Works well, but will this not need tests and version increments?

2021-12-10 10:58 UTC, EmmaLRussell commented
> Works well, but will this not need tests and version increments?

Yeah, should do a version increment actually, since it does change behaviour. Testing is kind of tricky, but yeah, I guess we could just test that the resulting selections can be modified.

2021-12-13 11:21 UTC, LekanAnni requested changes
I think it will be more natural to remove .freezeResponse() from the api call and freeze the bit that needs freezing.

2021-12-13 11:21 UTC, LekanAnni commented on src/app/static/src/app/store/modelCalibrate/actions.ts
>  import {freezer} from "../../utils";
unused import

2021-12-13 13:06 UTC, Nicolas-Dolan approved these changes
Works well for me. I think taking this whitelist approach with regard to properties to be unfrozen is the way to go.

2021-12-13 13:15 UTC, hillalex requested changes
Yes that makes sense re barchart, we ought not to be mutating props, oops! In the meantime this fix should do the job.

2021-12-13 13:15 UTC, hillalex commented on src/app/static/src/app/store/modelCalibrate/actions.ts
> +                    const unfrozenDefaultOptions= Object.keys(defaults.selected_filter_options)
So is it only the `response.data` object that we want frozen here? In which case I agree with Lekan that simply removing the `freezeResponse` call and doing `const data = freeze(response.data)` would be more parsimonious.

2021-12-13 13:17 UTC, hillalex approved these changes

2021-12-13 15:14 UTC, EmmaLRussell commented
Ticket for addressing the vue-charts bug: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2845

2021-12-13 17:50 UTC, LekanAnni approved these changes

2021-12-14 09:43 UTC, merged