mrc-1264 Add language toggle to login page
mrc-ide/hint pull request #714
Opened 2022-06-17 12:02 UTC by Nicolas-Dolan

## Description

Please describe your changes here

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2022-06-17 14:07 UTC, EmmaLRussell reviewed
I can completely see why you've taken this approach! But there's a couple of things I don't like about it:
1. difficult to test "floating" js which shoul really be in a component
2. keeping language in two separate places in localstorage and having to bodge between them, 

We actually already have precedent for 1. in the way that the forgotPassword/resetPassword templates works. This has a component and its own Vue app (configured in webpack.config.js). It has language toggle built in, and can use locales to do translations. I think we should follow this same pattern for the login page.  

This does not solve 2. The language selected in the reset password page does not survive into other pages. So rather than trying to fix this here just for the login case, I think we should consider that outside the scope of the ticket and solve that for everything in one go. I think probably the answer is to keep language outside the project state, and keep it as a separate value (as you have done here, but ending the use of the language in the state - it's always seemed weird to me that loading a project can change your language preference). 

We should probably discuss the generic language issue, with Rob and Lekan too, at Monday's planning session. But for this ticket I'd definitly advocate for the resetPassword approach.

2022-06-30 08:33 UTC, EmmaLRussell commented on src/app/static/src/tests/components/login.test.ts
> +        expect(wrapper.vm.$data.email).toBe("test")
You can usually get this with `(wrapper.find("whatever").element as HTMLInputElement).value` - more generally casting `.element` to a particular HTMLElement subtype is a really useful way of getting properties that aren't available on the wrapper interface. Here's an example: https://github.com/mrc-ide/hint/blob/1645dc1761898800313a566407195c3b96efc974/src/app/static/src/tests/directives/translate.test.ts#L52

2022-06-30 08:34 UTC, EmmaLRussell commented on src/app/static/src/tests/components/login.test.ts
> +    // it("continue as guest is set in session storage", async () => {
The localStorageManager tests use `spyOn`: https://github.com/mrc-ide/hint/blob/master/src/app/static/src/tests/localStorageManager.test.ts#L189

2022-06-30 16:37 UTC, EmmaLRussell requested changes
This looks good to me, but I think you can save yourself a bit of pain around the template/render function.

2022-06-30 16:37 UTC, EmmaLRussell commented on src/app/static/templates/login.ftl
> +<div id="app" title="${title}" app-title="${appTitle}" continue-to="${continueTo}" username="${username}" error="${error}"></div>
Our usual pattern here, would be to put the "app" id on a div containing a <login> element with all the props on. That way you shoudn't need your render method in login,ts.
```suggestion
<div id="app" >
    <login title="${title}" app-title="${appTitle}" continue-to="${continueTo}" username="${username}" error="${error}"></login>
</div>
```

2022-06-30 16:37 UTC, EmmaLRussell commented on src/app/static/src/app/login.ts
> +        })
See comment on the template - shouldn't need this

2022-06-30 16:37 UTC, EmmaLRussell commented on src/app/static/src/app/login.ts
> +    props: ["title", "appTitle", "username", "continueTo", "error"],
Shouldn't need these props if you make suggested template change

2022-07-05 09:27 UTC, EmmaLRussell approved these changes
Thanks!

2022-07-07 15:57 UTC, LekanAnni requested changes
Looks great, I think you have one more translation to do as seen in the screenshot below, including `Username or password is incorrect` text

![Screenshot 2022-07-07 at 16 53 08](https://user-images.githubusercontent.com/4240748/177818049-599c327a-a9d3-4152-8e60-310c8789823d.png)

2022-07-15 10:47 UTC, Nicolas-Dolan commented on src/app/static/src/tests/components/login.test.ts
> +        expect(wrapper.find("#error").text()).toBe("test error")
For some reason, whenever I try to test the translated errors, only the translation key comes through (eg, "badUsernamePassword"). It works as expected when testing manually though. To test, enter a correct password and change the language.

2022-07-15 13:24 UTC, LekanAnni requested changes
I think you want to translate from backend in ErrorMessageBundles

see as other data coming from backend are translated https://github.com/mrc-ide/hint/tree/master/src/app/src/main/resources

2022-07-15 13:54 UTC, Nicolas-Dolan commented
> I think you want to translate from backend in ErrorMessageBundles
> 
> see as other data coming from backend are translated https://github.com/mrc-ide/hint/tree/master/src/app/src/main/resources

Not sure this would work as the backend has no knowledge of the language set on the login page.

2022-07-15 14:34 UTC, LekanAnni commented
> > I think you want to translate from backend in ErrorMessageBundles
> > see as other data coming from backend are translated https://github.com/mrc-ide/hint/tree/master/src/app/src/main/resources
> 
> Not sure this would work as the backend has no knowledge of the language set on the login page. I may be wrong, I'll investigate.

You may have to reuse below code in LoginController 

```
    private fun getBundle(request: WebRequest): ResourceBundle
    {
        val language = request.getHeader("Accept-Language") ?: "en"
        return ResourceBundle.getBundle("ErrorMessageBundle", Locale(language))
    }
```

see file https://github.com/mrc-ide/hint/blob/dd6bac39074f8b781dd214bc065e40d01619354f/src/app/src/main/kotlin/org/imperial/mrc/hint/exceptions/HintExceptionHandler.kt#L77

2022-07-15 14:41 UTC, Nicolas-Dolan commented
> > > I think you want to translate from backend in ErrorMessageBundles
> > > see as other data coming from backend are translated https://github.com/mrc-ide/hint/tree/master/src/app/src/main/resources
> > 
> > 
> > Not sure this would work as the backend has no knowledge of the language set on the login page. I may be wrong, I'll investigate.
> 
> You may have to reuse below code in LoginController
> 
> ```
>     private fun getBundle(request: WebRequest): ResourceBundle
>     {
>         val language = request.getHeader("Accept-Language") ?: "en"
>         return ResourceBundle.getBundle("ErrorMessageBundle", Locale(language))
>     }
> ```
> 
> see file
> 
> https://github.com/mrc-ide/hint/blob/dd6bac39074f8b781dd214bc065e40d01619354f/src/app/src/main/kotlin/org/imperial/mrc/hint/exceptions/HintExceptionHandler.kt#L77

I played around with it and might be possible to get that to work, but I actually think it's better to translate the errors on the frontend like we do with everything else. If we send the errors pretranslated from the backend, we'd have to request them again if the user changes their language, which I'm not sure is possible. The issue I was having with testing earlier was due to a typo, which I've now fixed.

2022-07-15 14:46 UTC, LekanAnni commented
> > > > I think you want to translate from backend in ErrorMessageBundles
> > > > see as other data coming from backend are translated https://github.com/mrc-ide/hint/tree/master/src/app/src/main/resources
> > > 
> > > 
> > > Not sure this would work as the backend has no knowledge of the language set on the login page. I may be wrong, I'll investigate.
> > 
> > 
> > You may have to reuse below code in LoginController
> > ```
> >     private fun getBundle(request: WebRequest): ResourceBundle
> >     {
> >         val language = request.getHeader("Accept-Language") ?: "en"
> >         return ResourceBundle.getBundle("ErrorMessageBundle", Locale(language))
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > see file
> > https://github.com/mrc-ide/hint/blob/dd6bac39074f8b781dd214bc065e40d01619354f/src/app/src/main/kotlin/org/imperial/mrc/hint/exceptions/HintExceptionHandler.kt#L77
> 
> I played around with it and might be possible to get that to work, but I actually think it's better to translate the errors on the frontend like we do with everything else. If we send the errors pretranslated from the backend, we'd have to request them again if the user changes their language, which I'm not sure is possible. The issue I was having with testing earlier was due to a typo, which I've now fixed.

I am not keen with translating backend behaviour in frontend. I strongly believe this should be translated from backend just like we translate other exceptions from backend. 

Your concern about language changes does not really affect the behaviour as login requests always go to the backend, which will then retrieve current language from headers.

2022-07-15 15:02 UTC, Nicolas-Dolan commented
> > > > > I think you want to translate from backend in ErrorMessageBundles
> > > > > see as other data coming from backend are translated https://github.com/mrc-ide/hint/tree/master/src/app/src/main/resources
> > > > 
> > > > 
> > > > Not sure this would work as the backend has no knowledge of the language set on the login page. I may be wrong, I'll investigate.
> > > 
> > > 
> > > You may have to reuse below code in LoginController
> > > ```
> > >     private fun getBundle(request: WebRequest): ResourceBundle
> > >     {
> > >         val language = request.getHeader("Accept-Language") ?: "en"
> > >         return ResourceBundle.getBundle("ErrorMessageBundle", Locale(language))
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > see file
> > > https://github.com/mrc-ide/hint/blob/dd6bac39074f8b781dd214bc065e40d01619354f/src/app/src/main/kotlin/org/imperial/mrc/hint/exceptions/HintExceptionHandler.kt#L77
> > 
> > 
> > I played around with it and might be possible to get that to work, but I actually think it's better to translate the errors on the frontend like we do with everything else. If we send the errors pretranslated from the backend, we'd have to request them again if the user changes their language, which I'm not sure is possible. The issue I was having with testing earlier was due to a typo, which I've now fixed.
> 
> I am not keen with translating backend behaviour in frontend. I strongly believe this should be translated from backend just like we translate other exceptions from backend.
> 
> Your concern about language changes does not really affect the behaviour as login requests always go to the backend, which will then retrieve current language from headers.

The scenario I was thinking about is: there is an error message on the page in English. The user changes the language to French. Everything translates except that error message.

2022-07-15 15:16 UTC, LekanAnni commented
> > > > > > I think you want to translate from backend in ErrorMessageBundles
> > > > > > see as other data coming from backend are translated https://github.com/mrc-ide/hint/tree/master/src/app/src/main/resources
> > > > > 
> > > > > 
> > > > > Not sure this would work as the backend has no knowledge of the language set on the login page. I may be wrong, I'll investigate.
> > > > 
> > > > 
> > > > You may have to reuse below code in LoginController
> > > > ```
> > > >     private fun getBundle(request: WebRequest): ResourceBundle
> > > >     {
> > > >         val language = request.getHeader("Accept-Language") ?: "en"
> > > >         return ResourceBundle.getBundle("ErrorMessageBundle", Locale(language))
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > see file
> > > > https://github.com/mrc-ide/hint/blob/dd6bac39074f8b781dd214bc065e40d01619354f/src/app/src/main/kotlin/org/imperial/mrc/hint/exceptions/HintExceptionHandler.kt#L77
> > > 
> > > 
> > > I played around with it and might be possible to get that to work, but I actually think it's better to translate the errors on the frontend like we do with everything else. If we send the errors pretranslated from the backend, we'd have to request them again if the user changes their language, which I'm not sure is possible. The issue I was having with testing earlier was due to a typo, which I've now fixed.
> > 
> > 
> > I am not keen with translating backend behaviour in frontend. I strongly believe this should be translated from backend just like we translate other exceptions from backend.
> > Your concern about language changes does not really affect the behaviour as login requests always go to the backend, which will then retrieve current language from headers.
> 
> The scenario I was thinking about is: there is an error message on the page in English. The user changes the language to French. Everything translates except that error message.

We can refresh login page when language changes. I think we should keep backend translation in backend and vice versa. @EmmaLRussell  what's your opinion ?

2022-07-18 10:07 UTC, EmmaLRussell commented
> We can refresh login page when language changes. I think we should keep backend translation in backend and vice versa. @EmmaLRussell what's your opinion ?

Yes, agreed, in general - if the error is coming from the backend originally it ought to be getting translated in the back end too, as we do for other errors in the errors bundle. The front end should send a language header,to get the translated message, and if the user updates language, while there is an error present, the error code should be available in the qs so refreshing the page to get the translated message for the new language should be possible (may required some backend changes to check for the qs).

2022-09-22 13:44 UTC, Nicolas-Dolan commented on src/app/src/main/kotlin/org/imperial/mrc/hint/controllers/LoginController.kt
> +}
A bit of could repetition here. Could be put in a util perhaps but I didn't feel it was worth it.

2022-09-23 15:20 UTC, LekanAnni requested changes
Looking good, 

Login page does not display error message in other languages. When I select French and use wrong login details, it returns error message in English. The page literarily refreshes every time and re-renders in English.

2022-09-23 15:20 UTC, LekanAnni commented on src/app/src/main/kotlin/org/imperial/mrc/hint/controllers/Controllers.kt
> +open class Controllers(val request: HttpServletRequest)
```suggestion
abstract class ControllerExtension(val request: HttpServletRequest)
```

2022-09-27 08:28 UTC, EmmaLRussell commented
Given that there seem to be tricky outstanding issues with this ticket, and that the primary login method is about to be completely overhauled so that this original login page won't be used any more *and* that Nick is leaving anyway, it feels like maybe we should put this PR on hold for now as other things are higher priority. It might be that we need to apply some of the lessons learned here to the login page which we're going to have to add for Auth0 login (supporting guest user etc) - we should clarify localisation requirements for that too! Thoughts @r-ash ?

2022-10-10 09:44 UTC, r-ash commented
> 

Yep agreed, let's put it on hold until switch to Auth0 has is completed

2023-05-26 09:10 UTC, r-ash commented
Closing this for now to tidy up the open PRs as it is quite out of date. It's linked up to the ticket so we can find it again when this comes back around as highest priority.

2023-05-26 09:10 UTC, closed without merging