Mrc 3123 - Populate model Run Id and calibrate options from project summary
mrc-ide/hint pull request #724
Opened 2022-07-20 20:41 UTC by LekanAnni

## Description

Please describe your changes here

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2022-08-17 09:39 UTC, EmmaLRussell requested changes
This works for me, but I think it can be simplified by allowing the post window.reload process to fetch results for you.

2022-08-18 09:38 UTC, LekanAnni commented on src/app/static/src/app/utils.ts
> +    ])
> 

Thanks, much better 👍

2022-08-18 13:37 UTC, EmmaLRussell approved these changes
Thanks, looks good!

2022-08-18 13:37 UTC, EmmaLRussell commented on src/app/static/src/app/hintVersion.ts
> +
rogue blank line!

2022-08-19 14:29 UTC, Nicolas-Dolan approved these changes

2022-08-22 13:03 UTC, merged