Add link to project news site
mrc-ide/hint pull request #770
Opened 2022-11-10 14:02 UTC by r-ash

## Description

This PR will add a link to the news site into the version number drop down and updates the styling of the version drop down to make it clearer that the version numbers themselves are not clickable

For the styling here I removed the `!important` attribute on the dropdown-item styling which then meant the non href and non  tabindex drop down items lost their styling (troubleshooting request and save json). I added tabindex attribute to these as from reading around it "indicates that its element can be focused" which makes sense as they are clickable actions. Let me know if this approach is not the ideal one though, my CSS & SASS knowledge is pretty bad

## Type of version change

Patches

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

2022-11-11 16:10 UTC, LekanAnni requested changes
Looking good, nearly there.

See my suggestions below

2022-11-11 16:10 UTC, LekanAnni commented on src/app/static/src/tests/components/header/hintrVersionMenu.test.ts
> +        expect(link.attributes("target")).toBe("_blank");
`expectTranslated(link, "News", "Nouvelles", "Notícias", store)`

You will need to test translated text.

2022-11-11 16:10 UTC, LekanAnni commented on src/app/static/src/scss/partials/header.scss
> +
You don't need a custom css

2022-11-11 16:10 UTC, LekanAnni commented on src/app/static/src/app/components/header/HintrVersionMenu.vue
> +        <span class="dropdown-item dropdown-item-inactive"> hint : v{{ hintVersion }}</span>
```suggestion
        <span class="dropdown-item disabled"> naomi    : v{{ hintrVersions.naomi }} </span>
        <span class="dropdown-item disabled"> hintr    : v{{ hintrVersions.hintr }} </span>
        <span class="dropdown-item disabled"> rrq      : v{{ hintrVersions.rrq }} </span>
        <span class="dropdown-item disabled"> traduire : v{{ hintrVersions.traduire }}</span>
        <span class="dropdown-item disabled"> hint : v{{ hintVersion }}</span>
```

2022-11-11 16:42 UTC, r-ash commented on src/app/static/src/app/components/header/HintrVersionMenu.vue
> +        <span class="dropdown-item dropdown-item-inactive"> hint : v{{ hintVersion }}</span>
o nice! Thanks

2022-11-15 09:48 UTC, LekanAnni approved these changes
LGTM 👍

2022-11-15 09:48 UTC, merged