remove jsonata + some styling, need tests still
mrc-ide/hint pull request #859
Opened 2023-07-24 16:47 UTC by M-Kusumgar

## Problems/motivation:
- Input time series was taking too long to update the graphs because of jsonata being slow

## New features/solutions:
- Stepper connectors are more centered
- Download button icon is now aligned to the center
- Jsonata has been removed and replaced with base typescript

## How PR should behave when tested:
- Input time series should be fast when switching between any of the filters

## How to run app:
1. Run the app according to the README

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2023-08-10 13:43 UTC, M-Kusumgar commented
ignore codecov, I haven't deleted any tests, we have the same amount of testing as before so should be the same coverage

2023-08-10 16:04 UTC, LekanAnni requested changes
Looking good,

* Looks like test coverage for this PR should be covered as they are actually real 😆
* Can you reduce use of `any` data types ?
* Overall, the functionality is satisfactory; however, there seems to be a minor issue with the presentation of the data using Benin data, as it appears slightly compressed.

I don't think I have done justice reviewing your PR, this one rattled me but I have added a few inline comments. PR also works

2023-08-15 12:51 UTC, M-Kusumgar commented on src/app/static/src/app/components/genericChart/Plotly.vue
> +        modeBarButtonsToRemove: ['zoom2d', 'pan2d', 'select2d', 'lasso2d', 'autoScale2d', 'resetScale2d', 'zoomIn2d', 'zoomOut2d']
done

2023-08-15 12:51 UTC, M-Kusumgar commented on src/app/static/src/app/components/genericChart/Plotly.vue
> +            inputData() {
removed

2023-08-15 13:40 UTC, EmmaLRussell approved these changes
As discussed: happy to leave it til future tickets to deal with renaming from GenericChart, and to refactor the monolithic `getData` method into something more digestible (could you create this ticket if it doesn't exist already?).

2023-08-15 16:10 UTC, M-Kusumgar commented
> refactor the monolithic `getData` method into something more digestible (could you create this ticket if it doesn't exist already?).

done, https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-4524/Refactor-the-getData-computed-value-into-nicer-code

2023-08-15 16:12 UTC, M-Kusumgar commented
in the interest of time, will be merging this in since it has one approval, but can look over this after merge into master

2023-08-15 16:12 UTC, merged