mrc-3328 Keep user's language preference outside project state
mrc-ide/hint pull request #866
Opened 2023-08-17 16:15 UTC by LekanAnni

## Description

This removes language state from getting stored in the backend and local storage. Add new key to local storage and monitor language alongside language state. The instruction on the ticket is a lot miss leading, I have been trying to solve this differently, trying to remove language from the state completely. 

We still need language to be in the state for reusability across the app, This PR keeps track of user language outside of projects, with additional key in local storage. 

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2023-09-13 10:50 UTC, EmmaLRussell reviewed
Looks great. Correctly reloads a project with the user's new language preference if it has changed since the project was saved. I think leaving the state value in place but loading it from local storage is a good call for minimising the code changes, 

One thing it doesn't do, which was suggested in the ticket, was to save the user's language preference from the Forgot Password page. But I think that;s not a high priority.

2023-09-13 10:50 UTC, EmmaLRussell commented on src/app/static/src/app/localStorageManager.ts
> +    getLanguageState = (): Language => {
```suggestion
    getLanguage = (): Language => {
```

2023-09-13 10:50 UTC, EmmaLRussell commented on src/app/static/src/app/localStorageManager.ts
> +    saveLanguageState = (lang: Language) => {
```suggestion
    saveLanguage = (lang: Language) => {
```

2023-09-13 10:50 UTC, EmmaLRussell commented on src/app/static/src/app/localStorageManager.ts
> +            return {...partialRootState, ...{language: this.getLanguageState()}}
```suggestion
            return {...partialRootState, language: this.getLanguageState()}
```

2023-09-13 11:35 UTC, M-Kusumgar requested changes
Code looks good, little bit confused about functionality. Now the language is just updated in local storage so the app doesn't update when you select a new language from the dropdown? Think we do need to retain that behaviour because currently if i select "fr" from the dropdown, nothing actually happens until i refresh the page

2023-09-13 16:27 UTC, M-Kusumgar approved these changes

2023-09-19 15:42 UTC, LekanAnni commented on src/app/static/src/app/localStorageManager.ts
> +    getLanguageState = (): Language => {
Done.

2023-09-19 15:42 UTC, LekanAnni commented on news.md.save
> +# hint 2.39.0
Done

2023-09-19 15:42 UTC, LekanAnni commented on src/app/static/src/app/localStorageManager.ts
> +    saveLanguageState = (lang: Language) => {
Done

2023-09-21 08:04 UTC, EmmaLRussell approved these changes

2023-10-30 15:25 UTC, merged