Add filters and plot controls UI
mrc-ide/hint pull request #935
Opened 2024-02-12 14:36 UTC by r-ash

## Description

This PR will add plot controls and filters into the model outputs UI. It should be
* Initialise all drop downs for the tab you're on
* Set their available options
* Set them to multi/single select (for filters)
* Set their initial values

## Type of version change

None

## Checklist

- [ ] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

2024-02-12 15:30 UTC, M-Kusumgar requested changes
Looking good, got a couple of comments, mainly about interaction with store and props in the components!

2024-02-12 15:30 UTC, M-Kusumgar commented on src/app/static/src/app/components/modelOutput/ModelOutput.vue
> +            return Object.keys(store.state.plotSelections) as PlotName[]
Can just get these from the array defined in plotSelections.ts, there's an array of what you're looking for, i don't think this needs to be computed

2024-02-12 15:30 UTC, M-Kusumgar commented on src/app/static/src/app/components/plots/Filter.vue
> +        selectedOptions: Object as PropType<FilterOption[]>
multiple and selectionOptions can be pulled out of state in this component, might be cleaner as this component would be in charge of that filter select

2024-02-12 15:30 UTC, M-Kusumgar commented on src/app/static/src/app/components/plots/Filter.vue
> +            return i18next.t("select", "en");
should you be pulling out what language it currently is in the state for this?

2024-02-12 15:30 UTC, M-Kusumgar commented on src/app/static/src/app/components/modelOutput/ModelOutput.vue
> +            <PlotControlSet :active-plot="selectedPlot"/>
I think we've stuck to kebab case for component names in hint, same in other files

2024-02-12 15:30 UTC, M-Kusumgar commented on src/app/static/src/app/store/plotSelections/plotSelections.ts
> +};
this logic is quite simple can be put into the component itself, i also just realised, while we were discussing I was a little hesitant on getters but i couldnt figure out why so i left it, i now realise why, they are typed as `any`s so you may have to type cast them in the component, i personally just like putting this logic in the computed in the component if it is this simple. I think most getters are like 2 lines ish in this PR, might be worth putting into components

2024-02-13 16:31 UTC, r-ash commented on src/app/static/src/app/components/modelOutput/ModelOutput.vue
> +        const selectedPlot = ref<PlotName>(plotNames.value[0]);
Put this into state and have each component read it from state

2024-02-13 16:40 UTC, r-ash commented on src/app/static/src/app/store/modelCalibrate/modelCalibrate.ts
> +        return filterAfterUseShapeRegions(type as FilterTypes, rootState).options;
Put this into the metadata fetch logic, as a shallow copy of the regions in the features. Then we can remove the getter here and just use the store in the component

2024-02-14 12:02 UTC, r-ash commented
Thanks for v useful comments, I've made those changes - it's looking much tidier now.

2024-02-14 12:24 UTC, M-Kusumgar approved these changes
Nice one! all looks good to me! will start using this now and let you know if any problems arise but from the testing seems all good

2024-02-14 13:53 UTC, M-Kusumgar commented on src/app/static/src/app/components/plots/Filter.vue
> +            multiple: filter.value.multiple,
I have changed this in my branch, we couldnt test it until the plot settings dropdowns changed values but in my branch this doesnt update, apparently we have to return computed values only as return in setup, so have to return `filter` here and do `.multiple` on that

2024-04-09 11:13 UTC, merged